FROM ubuntu:20.04
ENV PYTHONUNBUFFERED 1
RUN echo "America/Los_Angeles" > /etc/timezone

RUN add-apt-repository universe && \
    apt update && \
    apt install freeglut3-dev -y -qq && \
    apt-get update && \
    apt-get install ubuntu-gnome-desktop -y -qq && \
