FROM dorowu/ubuntu-desktop-lxde-vnc:bionic
ENV PYTHONUNBUFFERED 1
RUN apt-get update -y -qq
RUN apt-get install python -y -qq
RUN apt-get install python3 -y -qq
RUN apt-get install python3-pip -y -qq

RUN makedir /prjroot
COPY requirements.txt /prjroot/
WORKDIR /prjroot
RUN pip3 install -r requirements.txt
COPY . /prjroot
